version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: pocketchef
      POSTGRES_PASSWORD: pocketchef
      POSTGRES_DB: pocketchef
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
